[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@velodrome/=lib/contracts/"
]

fs_permissions = [{ access = "read-write", path = "./"}]

via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
bsc = "${BSC_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
bsc = { key = "${BSC_SCAN_API_KEY}", url = "${BSC_ETHERSCAN_VERIFIER_URL}" }
optimism = { key = "${OPTIMISM_SCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}" }
base = { key = "${BASE_SCAN_API_KEY}", url = "${BASE_ETHERSCAN_VERIFIER_URL}" }
